# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='frame_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
