# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180831_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='is_spare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frame',
            name='is_strike',
            field=models.BooleanField(default=False),
        ),
    ]
