# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_frame_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='frame_count',
        ),
        migrations.AddField(
            model_name='frame',
            name='is_last_frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
